<!--THIS FILE IS GENERATED BY `./blog/build.js` DON'T EDIT HERE-->
<template>
  <div>
  <div class="header-padding"></div>
  <div class="article-wrapper" id="blog-index">
    <h1>{{ $t('siteBlog.title') }}</h1>
    <div class="subtitle" v-html="$t('siteBlog.subtitle')"></div>
    <router-link class="article-link" to="/blog/bft-the-most-secure-proof-of-stake">
      <div class="article-title">BFT: The Most Secure Proof-of-Stake</div>
      <div class="article-excerpt">Many people have rallied against the use of PoS, claiming it is impossible to secure. But that is simply not true. Using BFT, you absolutely can secure PoS.  It’s just that we haven’t seen any BFT-PoS public blockchains yet.</div>
      <div class="article-date">Posted on November 15, 2016</div>
    </router-link>
    <router-link class="article-link" to="/blog/purpose-of-cosmos">
      <div class="article-title">Purpose of Cosmos</div>
      <div class="article-excerpt">Cosmos is a culmination of lessons of prior cryptocurrencies. It's designed to be extended to incorporate future innovations. It's a distributed ledger platform suitable for generations to come.</div>
      <div class="article-date">Posted on August 31, 2016</div>
    </router-link>
  </div><!--article-wrapper-->
  </div>
</template>
<script>
export default {
  head: {
    title () {
      return {
        inner: this.$t('siteBlog.title'),
        separator: '-',
        complement: 'Cosmos - ' + this.$t('site.networkOfBlockchains')
      }
    }
  }
}
</script>
