<!--THIS FILE IS GENERATED BY `./blog/build.js` DO NOT EDIT HERE-->
<template>
  <div class="header-padding"></div>
  <div class="article-wrapper" id="blog-index">
    <h1>Cosmos Blog</h1>
    <div class="subtitle"><a href="/static/feed.xml">Subscribe</a> for the latest updates.</div>
    <a class="article-link" v-link="{ path: '/blog/purpose-of-cosmos'}">
      <div class="article-title">Purpose of Cosmos</div>
      <div class="article-excerpt">Cosmos is a culmination of lessons of prior cryptocurrencies. It's designed to be extended to incorporate future innovations. It's a distributed ledger platform suitable for generations to come.</div>
      <div class="article-date">Posted on August 31, 2016</div>
    </a>
  </div><!--article-wrapper-->
</template>
<script>
export default {
  head: {
    title: {
      inner: 'Blog'
    }
  }
}
</script>
