<template>
  <!--THIS FILE IS GENERATED BY `npm run blog` DO NOT EDIT HERE-->
  <div class="header-padding"></div>
  <div class="article-wrapper" id="blog-index">
    <h1>Cosmos Blog</h1>
    <a class="article-link" v-link="{ path: '/blog/purpose-of-cosmos'}">
      <h3>Purpose of Cosmos</h3>
    </a>
    <p>2016-08-31</p>
    <a class="article-link" v-link="{ path: '/blog/disclaimers-for-crowdfund-participants'}">
      <h3>Disclaimers for Crowdfund Participants</h3>
    </a>
    <p>2016-07-20</p>
    <a class="article-link" v-link="{ path: '/blog/just-a-test'}">
      <h3>Just a Test</h3>
    </a>
    <p>2016-04-04</p>
  </div><!--article-wrapper-->
</template>