module.exports = exports = function (post) {
  let facebookUrl = "`https://www.facebook.com/sharer/sharer.php?u=${window.location.href}`"
  let twitterUrl = "`https://twitter.com/home?status=" + encodeURI(post.title) + "%20${window.location.href}`"

  // set up the vue file
  let f = '<!--THIS FILE IS GENERATED BY `./blog/vueTemplatePost.js` DO NOT EDIT HERE-->\n'
  f += '<template>\n'
  f += '  <article-back-btn></article-back-btn>\n'
  f += '  <div class="header-padding"></div>\n'
  f += '  <div class="article-wrapper">\n'
  f += `    <h1>${post.title}</h1>\n\n`
  f += `    <div class="subtitle">${post.dateFriendly} by ${post.author}</div>\n\n`
  f +=      post.body
  f += '    <article-footer :facebook-url="facebookUrl" :twitter-url="twitterUrl"></article-footer>\n'
  f += '  </div><!--article-wrapper-->\n'
  f += '</template>\n'
  f += '<script>\n'
  f += 'import ArticleBackBtn from \'../partials/ArticleBackBtn.vue\'\n'
  f += 'import ArticleFooter from \'../partials/ArticleFooter.vue\'\n'
  f += 'export default {\n'
  f += '  components: {\n'
  f += '    ArticleBackBtn,\n'
  f += '    ArticleFooter\n'
  f += '  },\n'
  f += '  data () {\n'
  f += '    return {\n'
  f += `      facebookUrl: ${facebookUrl},\n`
  f += `      twitterUrl: ${twitterUrl}\n`
  f += '    }\n'
  f += '  },\n'
  f += '  head: {\n'
  f += '    title: {\n'
  f += `      inner: '${post.title}'\n`
  f += '    }\n'
  f += '  }\n'
  f += '}\n'
  f += '</script>\n'

  return f
}
