<template>
  <!--THIS FILE IS GENERATED BY `npm run blog` DO NOT EDIT HERE-->
  <div class="header-padding"></div>
  <div class="article-wrapper">
<h1>Just a Test</h1>

<div class="subtitle">2016-04-04 by Peng Zhong</div>

<p>Here is some markdown data. This is <strong>just</strong> a <em>test</em>.</p>
<ul>
<li>One</li>
<li>Two</li>
<li>Three</li>
</ul>
<ol>
<li>Four</li>
<li>Five</li>
<li>Six</li>
</ol>
  </div><!--article-wrapper-->
</template>