<template>
  <!--THIS FILE IS GENERATED BY `npm run blog` DO NOT EDIT HERE-->
  <div class="header-padding"></div>
  <div class="article-wrapper">
<h1>Test Post</h1>

<div class="subtitle">June 8, 2016 by Peng Zhong</div>

<p>Example post.</p>
<h2>A Couple Lists</h2>
<ol>
<li>One</li>
<li>Five</li>
<li>Seven</li>
</ol>
<ul>
<li>Important Point</li>
<li>Important Point Two</li>
<li>Important Point Three</li>
</ul>
<h3>An interesting aside</h3>
<p>The text goes here.</p>
<h2>Conclusion</h2>
<p>The text goes here.</p>
  </div><!--article-wrapper-->
</template>
<script>
export default {
  created () { document.title = 'Test Post - Cosmos' }
}
</script>
