<!--THIS FILE IS GENERATED BY `./blog/vueTemplatePost.js` DO NOT EDIT HERE-->
<template>
  <article-back-btn></article-back-btn>
  <div class="header-padding"></div>
  <div class="article-wrapper">
    <h1>Test Post</h1>

    <div class="subtitle">June 8, 2016 by Peng Zhong</div>

<p>Example post.</p>
<h2>A Couple Lists</h2>
<p>Just a a couple of lists below this, please ignore.</p>
<ol>
<li>One</li>
<li>Five</li>
<li>Seven</li>
</ol>
<ul>
<li>Important Point</li>
<li>Important Point Two</li>
<li>Important Point Three</li>
</ul>
<h3>An interesting aside</h3>
<p>The text goes here.</p>
<h2>Conclusion</h2>
<p>The text goes here.</p>
    <article-footer :facebook-url="facebookUrl" :twitter-url="twitterUrl"></article-footer>
  </div><!--article-wrapper-->
</template>
<script>
import ArticleBackBtn from '../partials/ArticleBackBtn.vue'
import ArticleFooter from '../partials/ArticleFooter.vue'
export default {
  components: {
    ArticleBackBtn,
    ArticleFooter
  },
  data () {
    return {
      facebookUrl: `https://www.facebook.com/sharer/sharer.php?u=${window.location.href}`,
      twitterUrl: `https://twitter.com/home?status=Test%20Post%20${window.location.href}`
    }
  },
  head: {
    title: {
      inner: 'Test Post'
    }
  }
}
</script>
